services:
  demo-client:
    build:
      context: ./
      dockerfile: app.Dockerfile
    volumes:
      - ./app:/app
    env_file: .env
    ports:
      - "8010:80"
    command: python /app/main.py
version: '2'
networks:
  default:
    external:
      name: dev-network
