services:
  demo-client:
    build:
      context: ./
      dockerfile: app.Dockerfile
    volumes:
      - ./app:/app
    env_file: .env
    ports:
      - "8010:80"
    command: python /app/main.py
    depends_on:
      database:
        condition: service_healthy
  database:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=8TV6xyAu6^7TP38rhB8s
      - MYSQL_DATABASE=demo
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=8TV6xyAu6^7TP38rhB8s
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
version: '2.1'
networks:
  default:
    external:
      name: dev-network
